<?php 
$tableParams = array(
	'tableId' 			=> 'hooks-table',
    'tableWidth'        => '3-wide',
    'summaryTableId'    => 'hooks-summary-table',
    'summaryTableWidth' => '1-narrow',
);
?>

<?php echo $this->zrayTable($tableParams); //zrayTableHtml ?>
<script type="text/javascript">
(function() {
	var storage = zray.getStorage('hooks');
	var storage_core = zray.getStorage('core_hooks');

	// create main table
	var maintable = zray.createTable(storage, jQuery('#<?php echo $tableParams['tableId']; ?>'));
	var cols = [
		{
			label:"#",
			"width":50,
			"propertyName": "id",
			sortable: true,
		},
		{
			"label": "Type",
			"propertyName": "hookType",
			"width":100,
			"sortable": true,
		},
		{
			"label": "Hook",
			"propertyName": "hookName",
			"sortable": true,
		},
		{
			"label": "Called By",
			"propertyName": "function",
			"sortable": true,
		},
		{
			"label": "Time (ms)",
			"propertyName": "executionTime",
			"width":70,
			"sortable": true
		},
		{
			"label": "Source",
			"propertyName": "hookSource",
			"sortable": true,
		},
		{
			"label": "Priority",
			"propertyName": "priority",
			"width":70,
			"sortable": true,
		}
	];
	if(zray.getFileActions && zray.showInIde){
		cols.push({
			label: 'File Name',
			tooltip: 'File actions',
			propertyName: 'filename',
			"sortable": true,
			getHtml: function(val, rec) {
				var showInIDEParams = {filePath: rec.file, line: rec.line, fullUrl: document.location.href};
				return zray.getFileActions(rec.fileLine, val, rec.file, showInIDEParams);
			}
		});
	}else{
		cols.push({
			"label": "File Name",
			"propertyName": "fileLine",
			"sortable": true,
		});
	}
	maintable.setColumns(cols);
	// create main table - end

	// create the summary table
	var summaryTable = zray.createSummaryTable(storage, jQuery('#<?php echo $tableParams['summaryTableId']; ?>'));
	
	var storedStateForCoreHooks = (zendDevBar.cookieParams && typeof (zendDevBar.cookieParams.displayWPCoreHooks) != 'undefined') ? 
				zendDevBar.cookieParams.displayWPCoreHooks : false; //false - the default of show core hooks
	var hideCoreHooks = (storedStateForCoreHooks == 0);
	
	summaryTable.setTableHeaderHtml('<th colspan="100%"><span id="zdb-show-hooks-core" class="zdb-show-summary-checkbox" title="Display entries for WordPress Core hooks">' +
				'<input type="checkbox" name="zdb-show-hooks-core" style="height:auto;"> Core <span id="zdb-total-silenced-logs"></span>'+
				'</span>Show</th>');
	// set the columns structure
	summaryTable.setColumns([
       {
            label: ' ',
            propertyName: 'hookType',
            width: 40,
            getHtml: function(value, record) {
                return summaryTable.createCheckboxColumn(value, record, summaryTable);
            }
       },
       {
           label: 'Hook Type',
           propertyName: 'hookType',
           width: '80%',
       },
       {
			label: 'Count',
			propertyName: 'count',
			width: '10%',
			attributes: {'class': 'zdb-numerical'},
			getHtml: function(val) {
				return '(' + val + ')';
			}
		}
    ]);
	
	jQuery('#zdb-show-hooks-core input[type="checkbox"]').prop('checked', storedStateForCoreHooks);

	// set by which column the user choice will filter
	summaryTable.setFilterColumn('hookType');

	// set callback function to create the table rows from all the data
	// return an array of rows, with columns that match to setColumns
	summaryTable.setUpdateCallback(function (data) {
		if (! data) return [];

		var aggregated = {};
		$zendDevBar.each(data, function(key, observer){
			observer.fileLine=observer.filename+':'+observer.line;
			//observer.actions='<a onclick="zray.showInIde(\''+observer.file+'\',\''+observer.line+'\')">show</a>';
			if (aggregated[observer.hookType]) {
				aggregated[observer.hookType]++;
			} else {
				aggregated[observer.hookType] = 1;
			}
		});

		if (Object.keys(aggregated).length == 0) {
			return [];
		}
		
		var normalized = [];
		normalized.push({'hookType': 'All', 'count': jQuery.map(aggregated, function(v){return v}).reduce(function(acc, item){return acc += item})});
		
		return normalized.concat($zendDevBar.map(aggregated, function(count, hookType){
			return {'hookType': hookType, 'count': count};
		}));
	});
	// create summary table - end

	// create pager and search
	zray.createPager(storage, jQuery('#<?php echo $params['pagerId']; ?>'));
	zray.createSearch(storage, jQuery('#<?php echo $params['searchId']; ?>'), maintable);
	
	zray.registerDataHandler('wordpress', 'core_hooks', function(extensionData, requestData) {
		storage_core.setData(extensionData);
	});
	
	zray.registerDataHandler('wordpress', 'hooks', function(extensionData, requestData) {
		storage.setData(extensionData);
		if(storedStateForCoreHooks){
			var coreHooksItems = zendDevBar.getStorage('core_hooks').detachData();
			zendDevBar.getStorage('hooks').addData(coreHooksItems);
		}
		//jQuery('[data-name="zrayExtension:wordpress/hooks"] .zdb-toolbar-info').append(' ('+extensionData.length+')');
	});
	
	
	$zendDevBar(document).on('click', '#zdb-show-hooks-core', function(event) {
			
		// avoid double event on checkbox click
		var $chkbx = $zendDevBar(':checkbox', this);
		if (event.target.type && event.target.type.toLowerCase() == 'checkbox') {
			$chkbx.prop('checked', !$chkbx.prop('checked'));
		}
		$chkbx.prop('checked', !$chkbx.prop('checked'));

		

		var $chkbx = $zendDevBar(':checkbox', this);
		// rename for convenience
		var newStateForHooksCoreParameter = $chkbx.prop('checked');
		var hideCoreHooks = !newStateForHooksCoreParameter;

		// remove / add core hooks to the data
		if (hideCoreHooks) {
			var coreHooksItems = zendDevBar.getStorage('hooks').detachData({hookCore:'1'});
			zendDevBar.getStorage('core_hooks').addData(coreHooksItems);
		} else {			
			var coreHooksItems = zendDevBar.getStorage('core_hooks').detachData();
			zendDevBar.getStorage('hooks').addData(coreHooksItems);
		}
		
		// store the state
		if (zendDevBar.cookieParams) {
			zendDevBar.cookieParams.displayWPCoreHooks = newStateForHooksCoreParameter;
			zendDevBar.updateCookieParams();
		}
		
		
	});
})();
</script>