<?php 
$tableParams = array(
	'tableId' 			=> 'hooks-table',
    'tableWidth'        => '3',
    'summaryTableId'    => 'hooks-summary-table',
    'summaryTableWidth' => '1',
);
?>

<?php echo $this->zrayTable($tableParams); //zrayTableHtml ?>

<script type="text/javascript">
(function() {
	var storage = zray.getStorage('hooks');

	// create main table
	var maintable = zray.createTable(storage, jQuery('#<?php echo $tableParams['tableId']; ?>'));
	var cols = [
		{
			"label": "Function",
			"propertyName": "function",
			"sortable": true,
		},
		{
			"label": "Hook Source",
			"propertyName": "hookSource",
			"sortable": true,
		},
		{
			"label": "Priority",
			"propertyName": "priority",
			"width":100,
			"sortable": true,
		},
		{
			"label": "Hook Type",
			"propertyName": "hookType",
			"width":100,
			"sortable": true,
		},
		{
			"label": "Time",
			"propertyName": "executionTime",
			"width":70,
			"sortable": true,
		}
	];
	if(zray.getFileActions && zray.showInIde){
		cols.push({
			label: 'File Name',
			tooltip: 'File actions',
			propertyName: 'filename',
			getHtml: function(val, rec) {
				var showInIDEParams = {filePath: rec.file, line: rec.line, fullUrl: document.location.href};
				return zray.getFileActions(rec.fileLine, val, rec.file, showInIDEParams);
			}
		});
	}else{
		cols.push({
			"label": "File Name",
			"propertyName": "fileLine",
		});
	}
	maintable.setColumns(cols);
	// create main table - end

	// create the summary table
	var summaryTable = zray.createSummaryTable(storage, jQuery('#<?php echo $tableParams['summaryTableId']; ?>'));

	// set the columns structure
	summaryTable.setColumns([
       {
            label: ' ',
            propertyName: 'hookType',
            width: 40,
            getHtml: function(value, record) {
                return summaryTable.createCheckboxColumn(value, record, summaryTable);
            }
       },
       {
           label: 'Hook Type',
           propertyName: 'hookType',
           width: '80%',
       },
       {
			label: 'Count',
			propertyName: 'count',
			width: '10%',
			attributes: {'class': 'zdb-numerical'},
			getHtml: function(val) {
				return '(' + val + ')';
			}
		}
    ]);

	// set by which column the user choice will filter
	summaryTable.setFilterColumn('hookType');

	// set callback function to create the table rows from all the data
	// return an array of rows, with columns that match to setColumns
	summaryTable.setUpdateCallback(function (data) {
		if (! data) return [];

		var aggregated = {};
		$zendDevBar.each(data, function(key, observer){
			observer.fileLine=observer.filename+':'+observer.line;
			//observer.actions='<a onclick="zray.showInIde(\''+observer.file+'\',\''+observer.line+'\')">show</a>';
			if (aggregated[observer.hookType]) {
				aggregated[observer.hookType]++;
			} else {
				aggregated[observer.hookType] = 1;
			}
		});

		if (Object.keys(aggregated).length == 0) {
			return [];
		}
		
		var normalized = [];
		normalized.push({'hookType': 'All', 'count': jQuery.map(aggregated, function(v){return v}).reduce(function(acc, item){return acc += item})});
		
		return normalized.concat($zendDevBar.map(aggregated, function(count, hookType){
			return {'hookType': hookType, 'count': count};
		}));
	});
	// create summary table - end

	// create pager and search
	zray.createPager(storage, jQuery('#<?php echo $params['pagerId']; ?>'));
	zray.createSearch(storage, jQuery('#<?php echo $params['searchId']; ?>'), maintable);
	
	zray.registerDataHandler('wordpress', 'hooks', function(extensionData, requestData) {
		storage.setData(extensionData);
		jQuery('[data-name="zrayExtension:wordpress/hooks"] .zdb-toolbar-info').append(' ('+extensionData.length+')');
	});
})();
</script>